// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: nextjs_stack.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunStackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStackRequest) Reset() {
	*x = RunStackRequest{}
	mi := &file_nextjs_stack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStackRequest) ProtoMessage() {}

func (x *RunStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nextjs_stack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStackRequest.ProtoReflect.Descriptor instead.
func (*RunStackRequest) Descriptor() ([]byte, []int) {
	return file_nextjs_stack_proto_rawDescGZIP(), []int{0}
}

func (x *RunStackRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunStackRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StackFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence    string                 `protobuf:"bytes,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Evidence      string                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackFinding) Reset() {
	*x = StackFinding{}
	mi := &file_nextjs_stack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackFinding) ProtoMessage() {}

func (x *StackFinding) ProtoReflect() protoreflect.Message {
	mi := &file_nextjs_stack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackFinding.ProtoReflect.Descriptor instead.
func (*StackFinding) Descriptor() ([]byte, []int) {
	return file_nextjs_stack_proto_rawDescGZIP(), []int{1}
}

func (x *StackFinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StackFinding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StackFinding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StackFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *StackFinding) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *StackFinding) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *StackFinding) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type RunStackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Findings      []*StackFinding        `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStackResponse) Reset() {
	*x = RunStackResponse{}
	mi := &file_nextjs_stack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStackResponse) ProtoMessage() {}

func (x *RunStackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nextjs_stack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStackResponse.ProtoReflect.Descriptor instead.
func (*RunStackResponse) Descriptor() ([]byte, []int) {
	return file_nextjs_stack_proto_rawDescGZIP(), []int{2}
}

func (x *RunStackResponse) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *RunStackResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunStackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunStackResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RunStackResponse) GetFindings() []*StackFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *RunStackResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunStackResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_nextjs_stack_proto protoreflect.FileDescriptor

const file_nextjs_stack_proto_rawDesc = "" +
	"\n" +
	"\x12nextjs_stack.proto\x12\x14surfacelab.nextjs.v1\x1a\x1cgoogle/protobuf/struct.proto\"^\n" +
	"\x0fRunStackRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xdf\x01\n" +
	"\fStackFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\tR\n" +
	"confidence\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\tR\bevidence\x121\n" +
	"\adetails\x18\a \x01(\v2\x17.google.protobuf.StructR\adetails\"\x82\x02\n" +
	"\x10RunStackResponse\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12>\n" +
	"\bfindings\x18\x05 \x03(\v2\".surfacelab.nextjs.v1.StackFindingR\bfindings\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error2o\n" +
	"\x12NextJSStackService\x12Y\n" +
	"\bRunStack\x12%.surfacelab.nextjs.v1.RunStackRequest\x1a&.surfacelab.nextjs.v1.RunStackResponseBPZNgithub.com/MariusBobitiu/surface-lab/services/nextjs-stack/transport/grpc;grpcb\x06proto3"

var (
	file_nextjs_stack_proto_rawDescOnce sync.Once
	file_nextjs_stack_proto_rawDescData []byte
)

func file_nextjs_stack_proto_rawDescGZIP() []byte {
	file_nextjs_stack_proto_rawDescOnce.Do(func() {
		file_nextjs_stack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nextjs_stack_proto_rawDesc), len(file_nextjs_stack_proto_rawDesc)))
	})
	return file_nextjs_stack_proto_rawDescData
}

var file_nextjs_stack_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nextjs_stack_proto_goTypes = []any{
	(*RunStackRequest)(nil),  // 0: surfacelab.nextjs.v1.RunStackRequest
	(*StackFinding)(nil),     // 1: surfacelab.nextjs.v1.StackFinding
	(*RunStackResponse)(nil), // 2: surfacelab.nextjs.v1.RunStackResponse
	(*structpb.Struct)(nil),  // 3: google.protobuf.Struct
}
var file_nextjs_stack_proto_depIdxs = []int32{
	3, // 0: surfacelab.nextjs.v1.RunStackRequest.metadata:type_name -> google.protobuf.Struct
	3, // 1: surfacelab.nextjs.v1.StackFinding.details:type_name -> google.protobuf.Struct
	1, // 2: surfacelab.nextjs.v1.RunStackResponse.findings:type_name -> surfacelab.nextjs.v1.StackFinding
	3, // 3: surfacelab.nextjs.v1.RunStackResponse.metadata:type_name -> google.protobuf.Struct
	0, // 4: surfacelab.nextjs.v1.NextJSStackService.RunStack:input_type -> surfacelab.nextjs.v1.RunStackRequest
	2, // 5: surfacelab.nextjs.v1.NextJSStackService.RunStack:output_type -> surfacelab.nextjs.v1.RunStackResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nextjs_stack_proto_init() }
func file_nextjs_stack_proto_init() {
	if File_nextjs_stack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nextjs_stack_proto_rawDesc), len(file_nextjs_stack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nextjs_stack_proto_goTypes,
		DependencyIndexes: file_nextjs_stack_proto_depIdxs,
		MessageInfos:      file_nextjs_stack_proto_msgTypes,
	}.Build()
	File_nextjs_stack_proto = out.File
	file_nextjs_stack_proto_goTypes = nil
	file_nextjs_stack_proto_depIdxs = nil
}
