// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: nextjs_stack.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NextJSStackService_RunStack_FullMethodName = "/surfacelab.nextjs.v1.NextJSStackService/RunStack"
)

// NextJSStackServiceClient is the client API for NextJSStackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NextJSStackServiceClient interface {
	RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error)
}

type nextJSStackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNextJSStackServiceClient(cc grpc.ClientConnInterface) NextJSStackServiceClient {
	return &nextJSStackServiceClient{cc}
}

func (c *nextJSStackServiceClient) RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunStackResponse)
	err := c.cc.Invoke(ctx, NextJSStackService_RunStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NextJSStackServiceServer is the server API for NextJSStackService service.
// All implementations must embed UnimplementedNextJSStackServiceServer
// for forward compatibility.
type NextJSStackServiceServer interface {
	RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error)
	mustEmbedUnimplementedNextJSStackServiceServer()
}

// UnimplementedNextJSStackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNextJSStackServiceServer struct{}

func (UnimplementedNextJSStackServiceServer) RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStack not implemented")
}
func (UnimplementedNextJSStackServiceServer) mustEmbedUnimplementedNextJSStackServiceServer() {}
func (UnimplementedNextJSStackServiceServer) testEmbeddedByValue()                            {}

// UnsafeNextJSStackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NextJSStackServiceServer will
// result in compilation errors.
type UnsafeNextJSStackServiceServer interface {
	mustEmbedUnimplementedNextJSStackServiceServer()
}

func RegisterNextJSStackServiceServer(s grpc.ServiceRegistrar, srv NextJSStackServiceServer) {
	// If the following call pancis, it indicates UnimplementedNextJSStackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NextJSStackService_ServiceDesc, srv)
}

func _NextJSStackService_RunStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NextJSStackServiceServer).RunStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NextJSStackService_RunStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NextJSStackServiceServer).RunStack(ctx, req.(*RunStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NextJSStackService_ServiceDesc is the grpc.ServiceDesc for NextJSStackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NextJSStackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surfacelab.nextjs.v1.NextJSStackService",
	HandlerType: (*NextJSStackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStack",
			Handler:    _NextJSStackService_RunStack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nextjs_stack.proto",
}
