# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nextjs_stack.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nextjs_stack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12nextjs_stack.proto\x12\x14surfacelab.nextjs.v1\x1a\x1cgoogle/protobuf/struct.proto\"L\n\x0fRunStackRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\x12)\n\x08metadata\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x9f\x01\n\x0cStackFinding\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\t\x12\x10\n\x08\x65vidence\x18\x06 \x01(\t\x12(\n\x07\x64\x65tails\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xc5\x01\n\x10RunStackResponse\x12\x0c\n\x04tool\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x03\x12\x34\n\x08\x66indings\x18\x05 \x03(\x0b\x32\".surfacelab.nextjs.v1.StackFinding\x12)\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\r\n\x05\x65rror\x18\x07 \x01(\t2o\n\x12NextJSStackService\x12Y\n\x08RunStack\x12%.surfacelab.nextjs.v1.RunStackRequest\x1a&.surfacelab.nextjs.v1.RunStackResponseBPZNgithub.com/MariusBobitiu/surface-lab/services/nextjs-stack/transport/grpc;grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nextjs_stack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/MariusBobitiu/surface-lab/services/nextjs-stack/transport/grpc;grpc'
  _globals['_RUNSTACKREQUEST']._serialized_start=74
  _globals['_RUNSTACKREQUEST']._serialized_end=150
  _globals['_STACKFINDING']._serialized_start=153
  _globals['_STACKFINDING']._serialized_end=312
  _globals['_RUNSTACKRESPONSE']._serialized_start=315
  _globals['_RUNSTACKRESPONSE']._serialized_end=512
  _globals['_NEXTJSSTACKSERVICE']._serialized_start=514
  _globals['_NEXTJSSTACKSERVICE']._serialized_end=625
# @@protoc_insertion_point(module_scope)
