# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import nextjs_stack_pb2 as nextjs__stack__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nextjs_stack_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NextJSStackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunStack = channel.unary_unary(
                '/surfacelab.nextjs.v1.NextJSStackService/RunStack',
                request_serializer=nextjs__stack__pb2.RunStackRequest.SerializeToString,
                response_deserializer=nextjs__stack__pb2.RunStackResponse.FromString,
                _registered_method=True)


class NextJSStackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NextJSStackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunStack': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStack,
                    request_deserializer=nextjs__stack__pb2.RunStackRequest.FromString,
                    response_serializer=nextjs__stack__pb2.RunStackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surfacelab.nextjs.v1.NextJSStackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surfacelab.nextjs.v1.NextJSStackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NextJSStackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surfacelab.nextjs.v1.NextJSStackService/RunStack',
            nextjs__stack__pb2.RunStackRequest.SerializeToString,
            nextjs__stack__pb2.RunStackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
