# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntool.proto\x12\x15surfacelab.scanner.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x1d\n\x0bToolRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\"\xbb\x01\n\nToolResult\x12\x0c\n\x04tool\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x03\x12\x30\n\x08\x66indings\x18\x05 \x03(\x0b\x32\x1e.surfacelab.scanner.v1.Finding\x12)\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\r\n\x05\x65rror\x18\x07 \x01(\t\"\x9a\x01\n\x07\x46inding\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\t\x12\x10\n\x08\x65vidence\x18\x06 \x01(\t\x12(\n\x07\x64\x65tails\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"%\n\x13\x42\x61selineScanRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\"7\n\x14\x42\x61selineScanResponse\x12\x0f\n\x07scan_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xd5\x03\n\x0bToolService\x12U\n\x0c\x43heckHeaders\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12Q\n\x08\x43heckTLS\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12Z\n\x11\x43heckFileExposure\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12T\n\x0b\x46ingerprint\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12j\n\x0fRunBaselineScan\x12*.surfacelab.scanner.v1.BaselineScanRequest\x1a+.surfacelab.scanner.v1.BaselineScanResponseBKZIgithub.com/MariusBobitiu/surface-lab/services/scanner/transport/grpc;grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZIgithub.com/MariusBobitiu/surface-lab/services/scanner/transport/grpc;grpc'
  _globals['_TOOLREQUEST']._serialized_start=67
  _globals['_TOOLREQUEST']._serialized_end=96
  _globals['_TOOLRESULT']._serialized_start=99
  _globals['_TOOLRESULT']._serialized_end=286
  _globals['_FINDING']._serialized_start=289
  _globals['_FINDING']._serialized_end=443
  _globals['_BASELINESCANREQUEST']._serialized_start=445
  _globals['_BASELINESCANREQUEST']._serialized_end=482
  _globals['_BASELINESCANRESPONSE']._serialized_start=484
  _globals['_BASELINESCANRESPONSE']._serialized_end=539
  _globals['_TOOLSERVICE']._serialized_start=542
  _globals['_TOOLSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
