// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: laravel_stack.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LaravelStackService_RunStack_FullMethodName = "/surfacelab.laravel.v1.LaravelStackService/RunStack"
)

// LaravelStackServiceClient is the client API for LaravelStackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaravelStackServiceClient interface {
	RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error)
}

type laravelStackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLaravelStackServiceClient(cc grpc.ClientConnInterface) LaravelStackServiceClient {
	return &laravelStackServiceClient{cc}
}

func (c *laravelStackServiceClient) RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunStackResponse)
	err := c.cc.Invoke(ctx, LaravelStackService_RunStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaravelStackServiceServer is the server API for LaravelStackService service.
// All implementations must embed UnimplementedLaravelStackServiceServer
// for forward compatibility.
type LaravelStackServiceServer interface {
	RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error)
	mustEmbedUnimplementedLaravelStackServiceServer()
}

// UnimplementedLaravelStackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaravelStackServiceServer struct{}

func (UnimplementedLaravelStackServiceServer) RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStack not implemented")
}
func (UnimplementedLaravelStackServiceServer) mustEmbedUnimplementedLaravelStackServiceServer() {}
func (UnimplementedLaravelStackServiceServer) testEmbeddedByValue()                             {}

// UnsafeLaravelStackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaravelStackServiceServer will
// result in compilation errors.
type UnsafeLaravelStackServiceServer interface {
	mustEmbedUnimplementedLaravelStackServiceServer()
}

func RegisterLaravelStackServiceServer(s grpc.ServiceRegistrar, srv LaravelStackServiceServer) {
	// If the following call pancis, it indicates UnimplementedLaravelStackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LaravelStackService_ServiceDesc, srv)
}

func _LaravelStackService_RunStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaravelStackServiceServer).RunStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaravelStackService_RunStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaravelStackServiceServer).RunStack(ctx, req.(*RunStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LaravelStackService_ServiceDesc is the grpc.ServiceDesc for LaravelStackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LaravelStackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surfacelab.laravel.v1.LaravelStackService",
	HandlerType: (*LaravelStackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStack",
			Handler:    _LaravelStackService_RunStack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "laravel_stack.proto",
}
