package models

const (
	SignalFrameworkWordPress            = "framework.wordpress"
	SignalFrameworkNextJS               = "framework.nextjs"
	SignalHostingCloudflare             = "hosting.cloudflare"
	SignalHostingVercel                 = "hosting.vercel"
	SignalHeaderServerPresent           = "header.server.present"
	SignalHeaderXPoweredByPresent       = "header.x_powered_by.present"
	SignalAssetsJSBundle                = "assets.js_bundle"
	SignalAssetsNextStatic              = "assets.next_static"
	SignalSecurityHSTSPresent           = "security.hsts.present"
	SignalSecurityCSPPresent            = "security.csp.present"
	SignalSecurityXContentTypePresent   = "security.x_content_type_options.present"
	SignalSecurityXFrameOptionsPresent  = "security.x_frame_options.present"
	SignalSecurityReferrerPolicyPresent = "security.referrer_policy.present"
	SignalSecurityHTTPS                 = "security.https"
	SignalSecurityHTTPRedirectsToHTTPS  = "security.http_redirects_to_https"
	SignalSecurityTLSCertValid          = "security.tls.cert_valid"
	SignalSecurityTLSCertExpiringSoon   = "security.tls.cert_expiring_soon"
	SignalSurfaceRobotsTxt              = "surface.robots_txt"
	SignalSurfaceSecurityTxt            = "surface.security_txt"
	SignalSurfaceSitemapXML             = "surface.sitemap_xml"
	SignalSurfaceLogin                  = "surface.login"
	SignalSurfaceAdmin                  = "surface.admin"
	SignalSurfaceAPI                    = "surface.api"
	SignalExposureEnvFile               = "exposure.env_file"
	SignalExposureGitConfig             = "exposure.git_config"
	SignalExposureBackupArchive         = "exposure.backup_archive"
	SignalTransportRedirected           = "transport.redirected"
	SignalTransportCanonicalURL         = "transport.canonical_url"
)
