// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: tool.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_CheckHeaders_FullMethodName      = "/surfacelab.scanner.v1.ToolService/CheckHeaders"
	ToolService_CheckTLS_FullMethodName          = "/surfacelab.scanner.v1.ToolService/CheckTLS"
	ToolService_CheckFileExposure_FullMethodName = "/surfacelab.scanner.v1.ToolService/CheckFileExposure"
	ToolService_Fingerprint_FullMethodName       = "/surfacelab.scanner.v1.ToolService/Fingerprint"
	ToolService_RunBaselineScan_FullMethodName   = "/surfacelab.scanner.v1.ToolService/RunBaselineScan"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolServiceClient interface {
	CheckHeaders(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error)
	CheckTLS(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error)
	CheckFileExposure(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error)
	Fingerprint(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error)
	RunBaselineScan(ctx context.Context, in *BaselineScanRequest, opts ...grpc.CallOption) (*BaselineScanResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) CheckHeaders(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResult)
	err := c.cc.Invoke(ctx, ToolService_CheckHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) CheckTLS(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResult)
	err := c.cc.Invoke(ctx, ToolService_CheckTLS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) CheckFileExposure(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResult)
	err := c.cc.Invoke(ctx, ToolService_CheckFileExposure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Fingerprint(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResult)
	err := c.cc.Invoke(ctx, ToolService_Fingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) RunBaselineScan(ctx context.Context, in *BaselineScanRequest, opts ...grpc.CallOption) (*BaselineScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaselineScanResponse)
	err := c.cc.Invoke(ctx, ToolService_RunBaselineScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
type ToolServiceServer interface {
	CheckHeaders(context.Context, *ToolRequest) (*ToolResult, error)
	CheckTLS(context.Context, *ToolRequest) (*ToolResult, error)
	CheckFileExposure(context.Context, *ToolRequest) (*ToolResult, error)
	Fingerprint(context.Context, *ToolRequest) (*ToolResult, error)
	RunBaselineScan(context.Context, *BaselineScanRequest) (*BaselineScanResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) CheckHeaders(context.Context, *ToolRequest) (*ToolResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHeaders not implemented")
}
func (UnimplementedToolServiceServer) CheckTLS(context.Context, *ToolRequest) (*ToolResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTLS not implemented")
}
func (UnimplementedToolServiceServer) CheckFileExposure(context.Context, *ToolRequest) (*ToolResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFileExposure not implemented")
}
func (UnimplementedToolServiceServer) Fingerprint(context.Context, *ToolRequest) (*ToolResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fingerprint not implemented")
}
func (UnimplementedToolServiceServer) RunBaselineScan(context.Context, *BaselineScanRequest) (*BaselineScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBaselineScan not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call pancis, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_CheckHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).CheckHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_CheckHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).CheckHeaders(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_CheckTLS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).CheckTLS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_CheckTLS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).CheckTLS(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_CheckFileExposure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).CheckFileExposure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_CheckFileExposure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).CheckFileExposure(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Fingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Fingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Fingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Fingerprint(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_RunBaselineScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaselineScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).RunBaselineScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_RunBaselineScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).RunBaselineScan(ctx, req.(*BaselineScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surfacelab.scanner.v1.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHeaders",
			Handler:    _ToolService_CheckHeaders_Handler,
		},
		{
			MethodName: "CheckTLS",
			Handler:    _ToolService_CheckTLS_Handler,
		},
		{
			MethodName: "CheckFileExposure",
			Handler:    _ToolService_CheckFileExposure_Handler,
		},
		{
			MethodName: "Fingerprint",
			Handler:    _ToolService_Fingerprint_Handler,
		},
		{
			MethodName: "RunBaselineScan",
			Handler:    _ToolService_RunBaselineScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tool.proto",
}
