// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: tool.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ToolRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolResult) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ToolResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ToolResult) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ToolResult) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence    string                 `protobuf:"bytes,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Evidence      string                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Finding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *Finding) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *Finding) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type BaselineScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineScanRequest) Reset() {
	*x = BaselineScanRequest{}
	mi := &file_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineScanRequest) ProtoMessage() {}

func (x *BaselineScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineScanRequest.ProtoReflect.Descriptor instead.
func (*BaselineScanRequest) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{3}
}

func (x *BaselineScanRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type BaselineScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineScanResponse) Reset() {
	*x = BaselineScanResponse{}
	mi := &file_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineScanResponse) ProtoMessage() {}

func (x *BaselineScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineScanResponse.ProtoReflect.Descriptor instead.
func (*BaselineScanResponse) Descriptor() ([]byte, []int) {
	return file_tool_proto_rawDescGZIP(), []int{4}
}

func (x *BaselineScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *BaselineScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_tool_proto protoreflect.FileDescriptor

const file_tool_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tool.proto\x12\x15surfacelab.scanner.v1\x1a\x1cgoogle/protobuf/struct.proto\"%\n" +
	"\vToolRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\xf8\x01\n" +
	"\n" +
	"ToolResult\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12:\n" +
	"\bfindings\x18\x05 \x03(\v2\x1e.surfacelab.scanner.v1.FindingR\bfindings\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xda\x01\n" +
	"\aFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\tR\n" +
	"confidence\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\tR\bevidence\x121\n" +
	"\adetails\x18\a \x01(\v2\x17.google.protobuf.StructR\adetails\"-\n" +
	"\x13BaselineScanRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"G\n" +
	"\x14BaselineScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xd5\x03\n" +
	"\vToolService\x12U\n" +
	"\fCheckHeaders\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12Q\n" +
	"\bCheckTLS\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12Z\n" +
	"\x11CheckFileExposure\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12T\n" +
	"\vFingerprint\x12\".surfacelab.scanner.v1.ToolRequest\x1a!.surfacelab.scanner.v1.ToolResult\x12j\n" +
	"\x0fRunBaselineScan\x12*.surfacelab.scanner.v1.BaselineScanRequest\x1a+.surfacelab.scanner.v1.BaselineScanResponseBKZIgithub.com/MariusBobitiu/surface-lab/services/scanner/transport/grpc;grpcb\x06proto3"

var (
	file_tool_proto_rawDescOnce sync.Once
	file_tool_proto_rawDescData []byte
)

func file_tool_proto_rawDescGZIP() []byte {
	file_tool_proto_rawDescOnce.Do(func() {
		file_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_proto_rawDesc), len(file_tool_proto_rawDesc)))
	})
	return file_tool_proto_rawDescData
}

var file_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tool_proto_goTypes = []any{
	(*ToolRequest)(nil),          // 0: surfacelab.scanner.v1.ToolRequest
	(*ToolResult)(nil),           // 1: surfacelab.scanner.v1.ToolResult
	(*Finding)(nil),              // 2: surfacelab.scanner.v1.Finding
	(*BaselineScanRequest)(nil),  // 3: surfacelab.scanner.v1.BaselineScanRequest
	(*BaselineScanResponse)(nil), // 4: surfacelab.scanner.v1.BaselineScanResponse
	(*structpb.Struct)(nil),      // 5: google.protobuf.Struct
}
var file_tool_proto_depIdxs = []int32{
	2, // 0: surfacelab.scanner.v1.ToolResult.findings:type_name -> surfacelab.scanner.v1.Finding
	5, // 1: surfacelab.scanner.v1.ToolResult.metadata:type_name -> google.protobuf.Struct
	5, // 2: surfacelab.scanner.v1.Finding.details:type_name -> google.protobuf.Struct
	0, // 3: surfacelab.scanner.v1.ToolService.CheckHeaders:input_type -> surfacelab.scanner.v1.ToolRequest
	0, // 4: surfacelab.scanner.v1.ToolService.CheckTLS:input_type -> surfacelab.scanner.v1.ToolRequest
	0, // 5: surfacelab.scanner.v1.ToolService.CheckFileExposure:input_type -> surfacelab.scanner.v1.ToolRequest
	0, // 6: surfacelab.scanner.v1.ToolService.Fingerprint:input_type -> surfacelab.scanner.v1.ToolRequest
	3, // 7: surfacelab.scanner.v1.ToolService.RunBaselineScan:input_type -> surfacelab.scanner.v1.BaselineScanRequest
	1, // 8: surfacelab.scanner.v1.ToolService.CheckHeaders:output_type -> surfacelab.scanner.v1.ToolResult
	1, // 9: surfacelab.scanner.v1.ToolService.CheckTLS:output_type -> surfacelab.scanner.v1.ToolResult
	1, // 10: surfacelab.scanner.v1.ToolService.CheckFileExposure:output_type -> surfacelab.scanner.v1.ToolResult
	1, // 11: surfacelab.scanner.v1.ToolService.Fingerprint:output_type -> surfacelab.scanner.v1.ToolResult
	4, // 12: surfacelab.scanner.v1.ToolService.RunBaselineScan:output_type -> surfacelab.scanner.v1.BaselineScanResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tool_proto_init() }
func file_tool_proto_init() {
	if File_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_proto_rawDesc), len(file_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tool_proto_goTypes,
		DependencyIndexes: file_tool_proto_depIdxs,
		MessageInfos:      file_tool_proto_msgTypes,
	}.Build()
	File_tool_proto = out.File
	file_tool_proto_goTypes = nil
	file_tool_proto_depIdxs = nil
}
