// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: wp_stack.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WordPressStackService_RunStack_FullMethodName = "/surfacelab.wpstack.v1.WordPressStackService/RunStack"
)

// WordPressStackServiceClient is the client API for WordPressStackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordPressStackServiceClient interface {
	RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error)
}

type wordPressStackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordPressStackServiceClient(cc grpc.ClientConnInterface) WordPressStackServiceClient {
	return &wordPressStackServiceClient{cc}
}

func (c *wordPressStackServiceClient) RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunStackResponse)
	err := c.cc.Invoke(ctx, WordPressStackService_RunStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordPressStackServiceServer is the server API for WordPressStackService service.
// All implementations must embed UnimplementedWordPressStackServiceServer
// for forward compatibility.
type WordPressStackServiceServer interface {
	RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error)
	mustEmbedUnimplementedWordPressStackServiceServer()
}

// UnimplementedWordPressStackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWordPressStackServiceServer struct{}

func (UnimplementedWordPressStackServiceServer) RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStack not implemented")
}
func (UnimplementedWordPressStackServiceServer) mustEmbedUnimplementedWordPressStackServiceServer() {}
func (UnimplementedWordPressStackServiceServer) testEmbeddedByValue()                               {}

// UnsafeWordPressStackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordPressStackServiceServer will
// result in compilation errors.
type UnsafeWordPressStackServiceServer interface {
	mustEmbedUnimplementedWordPressStackServiceServer()
}

func RegisterWordPressStackServiceServer(s grpc.ServiceRegistrar, srv WordPressStackServiceServer) {
	// If the following call pancis, it indicates UnimplementedWordPressStackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WordPressStackService_ServiceDesc, srv)
}

func _WordPressStackService_RunStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordPressStackServiceServer).RunStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WordPressStackService_RunStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordPressStackServiceServer).RunStack(ctx, req.(*RunStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordPressStackService_ServiceDesc is the grpc.ServiceDesc for WordPressStackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordPressStackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surfacelab.wpstack.v1.WordPressStackService",
	HandlerType: (*WordPressStackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStack",
			Handler:    _WordPressStackService_RunStack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wp_stack.proto",
}
