// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: php_stack.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PHPStackService_RunStack_FullMethodName = "/surfacelab.php.v1.PHPStackService/RunStack"
)

// PHPStackServiceClient is the client API for PHPStackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PHPStackServiceClient interface {
	RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error)
}

type pHPStackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPHPStackServiceClient(cc grpc.ClientConnInterface) PHPStackServiceClient {
	return &pHPStackServiceClient{cc}
}

func (c *pHPStackServiceClient) RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunStackResponse)
	err := c.cc.Invoke(ctx, PHPStackService_RunStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PHPStackServiceServer is the server API for PHPStackService service.
// All implementations must embed UnimplementedPHPStackServiceServer
// for forward compatibility.
type PHPStackServiceServer interface {
	RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error)
	mustEmbedUnimplementedPHPStackServiceServer()
}

// UnimplementedPHPStackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPHPStackServiceServer struct{}

func (UnimplementedPHPStackServiceServer) RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStack not implemented")
}
func (UnimplementedPHPStackServiceServer) mustEmbedUnimplementedPHPStackServiceServer() {}
func (UnimplementedPHPStackServiceServer) testEmbeddedByValue()                         {}

// UnsafePHPStackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PHPStackServiceServer will
// result in compilation errors.
type UnsafePHPStackServiceServer interface {
	mustEmbedUnimplementedPHPStackServiceServer()
}

func RegisterPHPStackServiceServer(s grpc.ServiceRegistrar, srv PHPStackServiceServer) {
	// If the following call pancis, it indicates UnimplementedPHPStackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PHPStackService_ServiceDesc, srv)
}

func _PHPStackService_RunStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PHPStackServiceServer).RunStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PHPStackService_RunStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PHPStackServiceServer).RunStack(ctx, req.(*RunStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PHPStackService_ServiceDesc is the grpc.ServiceDesc for PHPStackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PHPStackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surfacelab.php.v1.PHPStackService",
	HandlerType: (*PHPStackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStack",
			Handler:    _PHPStackService_RunStack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "php_stack.proto",
}
