// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: shopify_stack.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopifyStackService_RunStack_FullMethodName = "/surfacelab.shopify.v1.ShopifyStackService/RunStack"
)

// ShopifyStackServiceClient is the client API for ShopifyStackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopifyStackServiceClient interface {
	RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error)
}

type shopifyStackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopifyStackServiceClient(cc grpc.ClientConnInterface) ShopifyStackServiceClient {
	return &shopifyStackServiceClient{cc}
}

func (c *shopifyStackServiceClient) RunStack(ctx context.Context, in *RunStackRequest, opts ...grpc.CallOption) (*RunStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunStackResponse)
	err := c.cc.Invoke(ctx, ShopifyStackService_RunStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopifyStackServiceServer is the server API for ShopifyStackService service.
// All implementations must embed UnimplementedShopifyStackServiceServer
// for forward compatibility.
type ShopifyStackServiceServer interface {
	RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error)
	mustEmbedUnimplementedShopifyStackServiceServer()
}

// UnimplementedShopifyStackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopifyStackServiceServer struct{}

func (UnimplementedShopifyStackServiceServer) RunStack(context.Context, *RunStackRequest) (*RunStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStack not implemented")
}
func (UnimplementedShopifyStackServiceServer) mustEmbedUnimplementedShopifyStackServiceServer() {}
func (UnimplementedShopifyStackServiceServer) testEmbeddedByValue()                             {}

// UnsafeShopifyStackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopifyStackServiceServer will
// result in compilation errors.
type UnsafeShopifyStackServiceServer interface {
	mustEmbedUnimplementedShopifyStackServiceServer()
}

func RegisterShopifyStackServiceServer(s grpc.ServiceRegistrar, srv ShopifyStackServiceServer) {
	// If the following call pancis, it indicates UnimplementedShopifyStackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopifyStackService_ServiceDesc, srv)
}

func _ShopifyStackService_RunStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopifyStackServiceServer).RunStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopifyStackService_RunStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopifyStackServiceServer).RunStack(ctx, req.(*RunStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopifyStackService_ServiceDesc is the grpc.ServiceDesc for ShopifyStackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopifyStackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surfacelab.shopify.v1.ShopifyStackService",
	HandlerType: (*ShopifyStackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStack",
			Handler:    _ShopifyStackService_RunStack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shopify_stack.proto",
}
